seed_everything: null
trainer:
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: ./output
      name: Fault_Public_Pretrained
      version: swinsimmim_base_m0.75
      default_hp_metric: false
  # checkpoint_callback: null
  enable_checkpointing: true
  callbacks:
      - class_path: pytorch_lightning.callbacks.ModelCheckpoint
        init_args:
          filename: best
          monitor: val/l1_loss_avg
          mode: min
          # save_last: true
          save_weights_only: true
          auto_insert_metric_name: false
      - class_path: pytorch_lightning.callbacks.LearningRateMonitor
        init_args:
          logging_interval: step
      - class_path: pytorch_lightning.callbacks.RichProgressBar
  default_root_dir: ./output
  gradient_clip_val: null
  gradient_clip_algorithm: null
  # process_position: 0
  num_nodes: 1
  devices: -1
  accelerator: gpu
  # auto_select_gpus: false
  tpu_cores: null
  ipus: null
  # log_gpu_memory: null
  # progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 2
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 3000
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  # flush_logs_every_n_steps: null
  log_every_n_steps: 1
  strategy:
    class_path: pytorch_lightning.strategies.DDPStrategy
    init_args: 
      find_unused_parameters: false
  sync_batchnorm: false
  precision: 16
  enable_model_summary: true
  # weights_summary: top
  # weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: true
  deterministic: false
  # reload_dataloaders_every_n_epochs: 0
  # reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: false
  detect_anomaly: false
  auto_scale_batch_size: false
  # prepare_data_per_node: null
  plugins: null
  # amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  # stochastic_weight_avg: false
model:
  class_path: __main__.SimMIMtrainer
  init_args:
    model_name: swinsimmim_base
    model_dict:
      img_size: [128, 128, 128]
      in_channels: 1
      depths: [2, 2, 2, 2]
      num_heads: [3, 6, 12, 24]
      feature_size: 48
      drop_rate: 0.0
      attn_drop_rate: 0.0
      dropout_path_rate: 0.0 
      normalize: true
      use_checkpoint: false
      spatial_dims: 3
      downsample: merging
      use_v2: false
      pretrained: null
      revise_keys: []
      masking_ratio: 0.75
data:
  class_path: data.Fault_dataset.FaultDataset
  init_args:
    is_ssl: true
    # real_data_root_dir: /home/zhangzr/FaultRecongnition/Fault_data/real_labeled_data/crop
    # simulate_data_root_dir: /home/zhangzr/FaultRecongnition/Fault_data/simulate_data
    public_data_root_dir: /gpfs/share/home/2001110054/ondemand/code/Fault_Recong/Fault_data/public_data/crop
    batch_size: 2
    val_batch_size: 1
    num_workers: 8
    dist: true
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001
    weight_decay: 0.0
lr_scheduler:
  class_path: optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
  init_args:
    warmup_epochs: 100
    max_epochs: 3000
    eta_min: 0.0
ckpt_path: null
